### PR TITLE
Bug 1299840 - Log requests against aggregator service

### PR DESCRIPTION
**Pull request by fbertsch**
@vitillo r?

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/python_mozaggregator/26)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mozaggregator/service.py, line 36 at r1](https://reviewable.io:443/reviews/mozilla/python_mozaggregator/26#-K_DiiRZ4syfRCjbv4bi:-K_DiiRZ4syfRCjbv4bj:b3stfmy) ([raw file](https://github.com/mozilla/python_mozaggregator/blob/3f628467801aff9c655a6f0aac2ea85285cc95cb/mozaggregator/service.py#L36)):*
> ```Python
> logger.setLevel(logging.INFO)
> 
> syslog = SysLogHandler(address=('logs5.papertrailapp.com', 47698))
> ```

How is authentication handled?

---

*[mozaggregator/service.py, line 81 at r1](https://reviewable.io:443/reviews/mozilla/python_mozaggregator/26#-K_DhAb8Y5dGO3ALHLsq:-K_DhAb9gLdHepXPN9pV:b2x1hlz) ([raw file](https://github.com/mozilla/python_mozaggregator/blob/3f628467801aff9c655a6f0aac2ea85285cc95cb/mozaggregator/service.py#L81)):*
> ```Python
>     """Log format: Referrer URL, Referrer, IP Address, URL
>     """
>     dat  = (request.values.get('url', ''),
> ```

s/dat/data

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_mozaggregator/26)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[mozaggregator/service.py, line 36 at r1](https://reviewable.io:443/reviews/mozilla/python_mozaggregator/26#-K_EJbvOnnJuUbwa6tpi:-K_EJbvOnnJuUbwa6tpj:bq8e7z8) ([raw file](https://github.com/mozilla/python_mozaggregator/blob/3f628467801aff9c655a6f0aac2ea85285cc95cb/mozaggregator/service.py#L36)):*
> ```Python
> logger.setLevel(logging.INFO)
> 
> syslog = SysLogHandler(address=('logs5.papertrailapp.com', 47698))
> ```

Also, ideally we shouldn't send logs during development or testing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_mozaggregator/26)*

**Comment by fbertsch** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mozaggregator/service.py, line 36 at r1](https://reviewable.io:443/reviews/mozilla/python_mozaggregator/26#-K_EJbvOnnJuUbwa6tpi:-K_EdLnhg7kG9dvL3RPS:b-896fix) ([raw file](https://github.com/mozilla/python_mozaggregator/blob/3f628467801aff9c655a6f0aac2ea85285cc95cb/mozaggregator/service.py#L36)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

Also, ideally we shouldn't send logs during development or testing. 
</blockquote></details>

Done.

---

*[mozaggregator/service.py, line 36 at r1](https://reviewable.io:443/reviews/mozilla/python_mozaggregator/26#-K_DiiRZ4syfRCjbv4bi:-K_EdMMBIiRas2kGc4wo:b-y5cqa7) ([raw file](https://github.com/mozilla/python_mozaggregator/blob/3f628467801aff9c655a6f0aac2ea85285cc95cb/mozaggregator/service.py#L36)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

How is authentication handled?
</blockquote></details>

Papertrail doesn't provide authentication. According to [0], the best alternative is to whitelist the server sending the messages once this goes to production.

[0] http://help.papertrailapp.com/discussions/questions/289-preventing-my-logs-being-injected-with-untrusted-information.html

---

*[mozaggregator/service.py, line 81 at r1](https://reviewable.io:443/reviews/mozilla/python_mozaggregator/26#-K_DhAb8Y5dGO3ALHLsq:-K_EdKh6iW9vzRMsavGB:b-896fix) ([raw file](https://github.com/mozilla/python_mozaggregator/blob/3f628467801aff9c655a6f0aac2ea85285cc95cb/mozaggregator/service.py#L81)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

s/dat/data
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_mozaggregator/26)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_mozaggregator/26)*

**Pull request merged**
