### PR TITLE
Bug 1286951 - Update mozaggregator to account for change in childPayl…

### PR DESCRIPTION
**Pull request by chutten**
…oads

When bug 1218576 lands, Firefox will start sending child histograms in
.processes.child.{keyedH|h}istograms
instead of
.childPayloads[i].{keyedH|h}istograms

Handle pings that have child histograms in either (or a mix of both) config.

### CODE REVIEW

**Comment by vitillo** [comment]
@maurodoglio could you review this patch since you reviewed the corresponding change for `python_moztelemetry`?

**Comment by chutten** [comment]
This probably isn't yet ready for review. 

I can't run the tests locally as I'm on Windows (no Ansible support on Windows, and running a virtualbox inside a virtualbox messes up the networking enough that I can't ssh into the inner vagrant vm). So I'm going to have to use travis to test it for me.

**Comment by maurodoglio** [comment]
@chutten can you please ping me/r? me again when it's ready?

**Comment by chutten** [comment]
I am aborting this attempt as it isn't working out and I've spent too much time trying to make it work.

**Pull request closed without merging**
