### PR TITLE
Bug 1316721 - Use Dataset API

### PR DESCRIPTION
**Pull request by fbertsch**
The get_pings API has been deprecated.

Our tests don't test this, but this works manually. @vitillo, r?

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/python_mozaggregator/20)

### CODE REVIEW

**Comment by fbertsch** [comment]
@vitillo Using a single Dataset call now. Verified that this works manually.

**Comment by vitillo** [comment]
As discussed on IRC let's double check that the same set of pings is returned as before.

**Comment by vitillo** [comment]
@fbertsch can we merge this?

**Comment by vitillo** [comment]
lgtm

**Pull request merged**
