### PR TITLE
bug 1510957 - Only show browser.search.* scalars to authed users.

### PR DESCRIPTION
**Pull request by chutten**
This will show these metrics only to authed users.

Or should we blacklist them fully?

### CODE REVIEW

**Comment by wlach** [comment]
I don't think this should appear on tmo at all. We generally lock down all search data, and this seems even more sensitive than other stuff we collect.

https://docs.telemetry.mozilla.org/datasets/search.html#permissions

**Comment by fbertsch** [comment]
I'll go with @wlach's expertise on this. It might be good for new search probes/events to all share the same category so we can blacklist them on common analysis tooling.

**Comment by Standard8** [comment]
From what Javaun said in the data review, I agree, blacklist sides like what we want to do here.

**Comment by fbertsch** [comment]
This is being tackled now in #130.

**Pull request closed without merging**
