### PR TITLE
Make missing scalars 404

### PR DESCRIPTION
**Pull request by fbertsch**
Bug 1432547

### CODE REVIEW

**Comment by fbertsch** [comment]
Part of the fix for https://github.com/mozilla/telemetry-dashboard/issues/382.

**Comment by fbertsch** [comment]
Current behavior is the service errors out, and you get a `500`. Getting a `404` should be parseable by `telemetry.js`. (right?)

**Comment by chutten** [comment]
(mostly, yes. There's handling for 404s in a couple of expected places, and no handling for 500)

**Comment by fbertsch** [comment]
Perfect. Looks like it now gets the "No data matches these filters and settings" for those scalars.

**Pull request merged**
