### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by robhudson**
I removed redis and pycrypto, and also used `pipdeptree` to find libs we don't use directly but are actually dependencies of other libraries and can be removed from the setup.py file.

### CODE REVIEW

**Comment by robhudson** [comment]
@fbertsch Do we even need the setup.py install requires? Is python_mozaggregator installed as a lib for some other service anywhere? If not, then I don't think it's necessary.

**Comment by fbertsch** [comment]
@robhudson the aggregator is installed on the clusters through pypi. Let's keep this for now, but we can move to a better deploy that's in line with what we do for python_mozetl: clone the repo in the cluster and run it from there, rather than install from pypi. Then we can remove the `install requires`. Do you want to make a bug for that?

**Comment by robhudson** [comment]
@fbertsch https://bugzilla.mozilla.org/show_bug.cgi?id=1447495

If you're ok with this PR aside from that it's blocked on merging for an approval.

**Comment by fbertsch** [comment]
@robhudson approved, but the build is still broken. If you have to make any significant changes to get it working again ping me for a re-review.

**Pull request merged**
